spring:
  profiles:
    active: local

---
spring:
  profiles: local

  boot:
    admin:
      client:
        url: http://localhost:30000
        instance:
          service-url: http://localhost:${server.port}
  r2dbc:
    url: r2dbc:postgresql://cp.c0tpohd5aalk.ap-northeast-2.rds.amazonaws.com:5432/cp?currentSchema=public
    username: cp
    password: cp2020!!

  dataSource:
    url: jdbc:postgresql://cp.c0tpohd5aalk.ap-northeast-2.rds.amazonaws.com:5432/cp?currentSchema=public
    username: cp
    password: cp2020!!

security:
  jwt:
    public-key: classpath:public.txt

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.r2dbc: DEBUG

server:
  port: 20001

---
